// Code generated by generator, DO NOT EDIT.
package main

import (
	"github.com/adarah/go-aoc/solutions/2021/day_01"
	"github.com/adarah/go-aoc/solutions/2021/day_02"
	"github.com/adarah/go-aoc/solutions/2021/day_03"
	"github.com/adarah/go-aoc/solutions/2021/day_04"
	"fmt"
)

func getImplementation(year, day uint) (Solution, error) {
	registry := map[string]Solution{
		"solutions/2021/day_01": &day_01.Solution{},
		"solutions/2021/day_02": &day_02.Solution{},
		"solutions/2021/day_03": &day_03.Solution{},
		"solutions/2021/day_04": &day_04.Solution{},
	}
	path := fmt.Sprintf("solutions/%d/day_%02d", year, day)
	solution, ok := registry[path]
	if !ok {
		return nil, fmt.Errorf("no solution found")
	}
	return solution, nil
}